version: '3.8'
services:
  backend:
    build:
      context: ./backend
    env_file:
      - .env
    ports:
      - "3001:3001"
    volumes:
      - ./backend/data:/app/data
  frontend:
    build:
      context: ./frontend
    env_file:
      - .env
    ports:
      - "3000:80"
    depends_on:
      - backend
